#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
pub const KHRONOS_SUPPORT_INT64: u32 = 1;
pub const KHRONOS_SUPPORT_FLOAT: u32 = 1;
pub const KHRONOS_MAX_ENUM: u32 = 2147483647;
pub const EGL_EGL_PROTOTYPES: u32 = 1;
pub const EGL_VERSION_1_0: u32 = 1;
pub const EGL_ALPHA_SIZE: u32 = 12321;
pub const EGL_BAD_ACCESS: u32 = 12290;
pub const EGL_BAD_ALLOC: u32 = 12291;
pub const EGL_BAD_ATTRIBUTE: u32 = 12292;
pub const EGL_BAD_CONFIG: u32 = 12293;
pub const EGL_BAD_CONTEXT: u32 = 12294;
pub const EGL_BAD_CURRENT_SURFACE: u32 = 12295;
pub const EGL_BAD_DISPLAY: u32 = 12296;
pub const EGL_BAD_MATCH: u32 = 12297;
pub const EGL_BAD_NATIVE_PIXMAP: u32 = 12298;
pub const EGL_BAD_NATIVE_WINDOW: u32 = 12299;
pub const EGL_BAD_PARAMETER: u32 = 12300;
pub const EGL_BAD_SURFACE: u32 = 12301;
pub const EGL_BLUE_SIZE: u32 = 12322;
pub const EGL_BUFFER_SIZE: u32 = 12320;
pub const EGL_CONFIG_CAVEAT: u32 = 12327;
pub const EGL_CONFIG_ID: u32 = 12328;
pub const EGL_CORE_NATIVE_ENGINE: u32 = 12379;
pub const EGL_DEPTH_SIZE: u32 = 12325;
pub const EGL_DRAW: u32 = 12377;
pub const EGL_EXTENSIONS: u32 = 12373;
pub const EGL_FALSE: u32 = 0;
pub const EGL_GREEN_SIZE: u32 = 12323;
pub const EGL_HEIGHT: u32 = 12374;
pub const EGL_LARGEST_PBUFFER: u32 = 12376;
pub const EGL_LEVEL: u32 = 12329;
pub const EGL_MAX_PBUFFER_HEIGHT: u32 = 12330;
pub const EGL_MAX_PBUFFER_PIXELS: u32 = 12331;
pub const EGL_MAX_PBUFFER_WIDTH: u32 = 12332;
pub const EGL_NATIVE_RENDERABLE: u32 = 12333;
pub const EGL_NATIVE_VISUAL_ID: u32 = 12334;
pub const EGL_NATIVE_VISUAL_TYPE: u32 = 12335;
pub const EGL_NONE: u32 = 12344;
pub const EGL_NON_CONFORMANT_CONFIG: u32 = 12369;
pub const EGL_NOT_INITIALIZED: u32 = 12289;
pub const EGL_PBUFFER_BIT: u32 = 1;
pub const EGL_PIXMAP_BIT: u32 = 2;
pub const EGL_READ: u32 = 12378;
pub const EGL_RED_SIZE: u32 = 12324;
pub const EGL_SAMPLES: u32 = 12337;
pub const EGL_SAMPLE_BUFFERS: u32 = 12338;
pub const EGL_SLOW_CONFIG: u32 = 12368;
pub const EGL_STENCIL_SIZE: u32 = 12326;
pub const EGL_SUCCESS: u32 = 12288;
pub const EGL_SURFACE_TYPE: u32 = 12339;
pub const EGL_TRANSPARENT_BLUE_VALUE: u32 = 12341;
pub const EGL_TRANSPARENT_GREEN_VALUE: u32 = 12342;
pub const EGL_TRANSPARENT_RED_VALUE: u32 = 12343;
pub const EGL_TRANSPARENT_RGB: u32 = 12370;
pub const EGL_TRANSPARENT_TYPE: u32 = 12340;
pub const EGL_TRUE: u32 = 1;
pub const EGL_VENDOR: u32 = 12371;
pub const EGL_VERSION: u32 = 12372;
pub const EGL_WIDTH: u32 = 12375;
pub const EGL_WINDOW_BIT: u32 = 4;
pub const EGL_VERSION_1_1: u32 = 1;
pub const EGL_BACK_BUFFER: u32 = 12420;
pub const EGL_BIND_TO_TEXTURE_RGB: u32 = 12345;
pub const EGL_BIND_TO_TEXTURE_RGBA: u32 = 12346;
pub const EGL_CONTEXT_LOST: u32 = 12302;
pub const EGL_MIN_SWAP_INTERVAL: u32 = 12347;
pub const EGL_MAX_SWAP_INTERVAL: u32 = 12348;
pub const EGL_MIPMAP_TEXTURE: u32 = 12418;
pub const EGL_MIPMAP_LEVEL: u32 = 12419;
pub const EGL_NO_TEXTURE: u32 = 12380;
pub const EGL_TEXTURE_2D: u32 = 12383;
pub const EGL_TEXTURE_FORMAT: u32 = 12416;
pub const EGL_TEXTURE_RGB: u32 = 12381;
pub const EGL_TEXTURE_RGBA: u32 = 12382;
pub const EGL_TEXTURE_TARGET: u32 = 12417;
pub const EGL_VERSION_1_2: u32 = 1;
pub const EGL_ALPHA_FORMAT: u32 = 12424;
pub const EGL_ALPHA_FORMAT_NONPRE: u32 = 12427;
pub const EGL_ALPHA_FORMAT_PRE: u32 = 12428;
pub const EGL_ALPHA_MASK_SIZE: u32 = 12350;
pub const EGL_BUFFER_PRESERVED: u32 = 12436;
pub const EGL_BUFFER_DESTROYED: u32 = 12437;
pub const EGL_CLIENT_APIS: u32 = 12429;
pub const EGL_COLORSPACE: u32 = 12423;
pub const EGL_COLORSPACE_S_RGB: u32 = 12425;
pub const EGL_COLORSPACE_LINEAR: u32 = 12426;
pub const EGL_COLOR_BUFFER_TYPE: u32 = 12351;
pub const EGL_CONTEXT_CLIENT_TYPE: u32 = 12439;
pub const EGL_DISPLAY_SCALING: u32 = 10000;
pub const EGL_HORIZONTAL_RESOLUTION: u32 = 12432;
pub const EGL_LUMINANCE_BUFFER: u32 = 12431;
pub const EGL_LUMINANCE_SIZE: u32 = 12349;
pub const EGL_OPENGL_ES_BIT: u32 = 1;
pub const EGL_OPENVG_BIT: u32 = 2;
pub const EGL_OPENGL_ES_API: u32 = 12448;
pub const EGL_OPENVG_API: u32 = 12449;
pub const EGL_OPENVG_IMAGE: u32 = 12438;
pub const EGL_PIXEL_ASPECT_RATIO: u32 = 12434;
pub const EGL_RENDERABLE_TYPE: u32 = 12352;
pub const EGL_RENDER_BUFFER: u32 = 12422;
pub const EGL_RGB_BUFFER: u32 = 12430;
pub const EGL_SINGLE_BUFFER: u32 = 12421;
pub const EGL_SWAP_BEHAVIOR: u32 = 12435;
pub const EGL_VERTICAL_RESOLUTION: u32 = 12433;
pub const EGL_VERSION_1_3: u32 = 1;
pub const EGL_CONFORMANT: u32 = 12354;
pub const EGL_CONTEXT_CLIENT_VERSION: u32 = 12440;
pub const EGL_MATCH_NATIVE_PIXMAP: u32 = 12353;
pub const EGL_OPENGL_ES2_BIT: u32 = 4;
pub const EGL_VG_ALPHA_FORMAT: u32 = 12424;
pub const EGL_VG_ALPHA_FORMAT_NONPRE: u32 = 12427;
pub const EGL_VG_ALPHA_FORMAT_PRE: u32 = 12428;
pub const EGL_VG_ALPHA_FORMAT_PRE_BIT: u32 = 64;
pub const EGL_VG_COLORSPACE: u32 = 12423;
pub const EGL_VG_COLORSPACE_S_RGB: u32 = 12425;
pub const EGL_VG_COLORSPACE_LINEAR: u32 = 12426;
pub const EGL_VG_COLORSPACE_LINEAR_BIT: u32 = 32;
pub const EGL_VERSION_1_4: u32 = 1;
pub const EGL_MULTISAMPLE_RESOLVE_BOX_BIT: u32 = 512;
pub const EGL_MULTISAMPLE_RESOLVE: u32 = 12441;
pub const EGL_MULTISAMPLE_RESOLVE_DEFAULT: u32 = 12442;
pub const EGL_MULTISAMPLE_RESOLVE_BOX: u32 = 12443;
pub const EGL_OPENGL_API: u32 = 12450;
pub const EGL_OPENGL_BIT: u32 = 8;
pub const EGL_SWAP_BEHAVIOR_PRESERVED_BIT: u32 = 1024;
pub const EGL_VERSION_1_5: u32 = 1;
pub const EGL_CONTEXT_MAJOR_VERSION: u32 = 12440;
pub const EGL_CONTEXT_MINOR_VERSION: u32 = 12539;
pub const EGL_CONTEXT_OPENGL_PROFILE_MASK: u32 = 12541;
pub const EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY: u32 = 12733;
pub const EGL_NO_RESET_NOTIFICATION: u32 = 12734;
pub const EGL_LOSE_CONTEXT_ON_RESET: u32 = 12735;
pub const EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT: u32 = 1;
pub const EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT: u32 = 2;
pub const EGL_CONTEXT_OPENGL_DEBUG: u32 = 12720;
pub const EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE: u32 = 12721;
pub const EGL_CONTEXT_OPENGL_ROBUST_ACCESS: u32 = 12722;
pub const EGL_OPENGL_ES3_BIT: u32 = 64;
pub const EGL_CL_EVENT_HANDLE: u32 = 12444;
pub const EGL_SYNC_CL_EVENT: u32 = 12542;
pub const EGL_SYNC_CL_EVENT_COMPLETE: u32 = 12543;
pub const EGL_SYNC_PRIOR_COMMANDS_COMPLETE: u32 = 12528;
pub const EGL_SYNC_TYPE: u32 = 12535;
pub const EGL_SYNC_STATUS: u32 = 12529;
pub const EGL_SYNC_CONDITION: u32 = 12536;
pub const EGL_SIGNALED: u32 = 12530;
pub const EGL_UNSIGNALED: u32 = 12531;
pub const EGL_SYNC_FLUSH_COMMANDS_BIT: u32 = 1;
pub const EGL_FOREVER: i32 = -1;
pub const EGL_TIMEOUT_EXPIRED: u32 = 12533;
pub const EGL_CONDITION_SATISFIED: u32 = 12534;
pub const EGL_SYNC_FENCE: u32 = 12537;
pub const EGL_GL_COLORSPACE: u32 = 12445;
pub const EGL_GL_COLORSPACE_SRGB: u32 = 12425;
pub const EGL_GL_COLORSPACE_LINEAR: u32 = 12426;
pub const EGL_GL_RENDERBUFFER: u32 = 12473;
pub const EGL_GL_TEXTURE_2D: u32 = 12465;
pub const EGL_GL_TEXTURE_LEVEL: u32 = 12476;
pub const EGL_GL_TEXTURE_3D: u32 = 12466;
pub const EGL_GL_TEXTURE_ZOFFSET: u32 = 12477;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X: u32 = 12467;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X: u32 = 12468;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y: u32 = 12469;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: u32 = 12470;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z: u32 = 12471;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: u32 = 12472;
pub const EGL_IMAGE_PRESERVED: u32 = 12498;
pub const __EGLEXT_H: u32 = 1;
pub const EGL_EGLEXT_VERSION: u32 = 20240909;
pub const EGL_KHR_CL_EVENT: u32 = 1;
pub const EGL_CL_EVENT_HANDLE_KHR: u32 = 12444;
pub const EGL_SYNC_CL_EVENT_KHR: u32 = 12542;
pub const EGL_SYNC_CL_EVENT_COMPLETE_KHR: u32 = 12543;
pub const EGL_KHR_CL_EVENT2: u32 = 1;
pub const EGL_KHR_CLIENT_GET_ALL_PROC_ADDRESSES: u32 = 1;
pub const EGL_KHR_CONFIG_ATTRIBS: u32 = 1;
pub const EGL_CONFORMANT_KHR: u32 = 12354;
pub const EGL_VG_COLORSPACE_LINEAR_BIT_KHR: u32 = 32;
pub const EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR: u32 = 64;
pub const EGL_KHR_CONTEXT_FLUSH_CONTROL: u32 = 1;
pub const EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR: u32 = 0;
pub const EGL_CONTEXT_RELEASE_BEHAVIOR_KHR: u32 = 8343;
pub const EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR: u32 = 8344;
pub const EGL_KHR_CREATE_CONTEXT: u32 = 1;
pub const EGL_CONTEXT_MAJOR_VERSION_KHR: u32 = 12440;
pub const EGL_CONTEXT_MINOR_VERSION_KHR: u32 = 12539;
pub const EGL_CONTEXT_FLAGS_KHR: u32 = 12540;
pub const EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR: u32 = 12541;
pub const EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR: u32 = 12733;
pub const EGL_NO_RESET_NOTIFICATION_KHR: u32 = 12734;
pub const EGL_LOSE_CONTEXT_ON_RESET_KHR: u32 = 12735;
pub const EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR: u32 = 1;
pub const EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR: u32 = 2;
pub const EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR: u32 = 4;
pub const EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR: u32 = 1;
pub const EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR: u32 = 2;
pub const EGL_OPENGL_ES3_BIT_KHR: u32 = 64;
pub const EGL_KHR_CREATE_CONTEXT_NO_ERROR: u32 = 1;
pub const EGL_CONTEXT_OPENGL_NO_ERROR_KHR: u32 = 12723;
pub const EGL_KHR_DEBUG: u32 = 1;
pub const EGL_OBJECT_THREAD_KHR: u32 = 13232;
pub const EGL_OBJECT_DISPLAY_KHR: u32 = 13233;
pub const EGL_OBJECT_CONTEXT_KHR: u32 = 13234;
pub const EGL_OBJECT_SURFACE_KHR: u32 = 13235;
pub const EGL_OBJECT_IMAGE_KHR: u32 = 13236;
pub const EGL_OBJECT_SYNC_KHR: u32 = 13237;
pub const EGL_OBJECT_STREAM_KHR: u32 = 13238;
pub const EGL_DEBUG_MSG_CRITICAL_KHR: u32 = 13241;
pub const EGL_DEBUG_MSG_ERROR_KHR: u32 = 13242;
pub const EGL_DEBUG_MSG_WARN_KHR: u32 = 13243;
pub const EGL_DEBUG_MSG_INFO_KHR: u32 = 13244;
pub const EGL_DEBUG_CALLBACK_KHR: u32 = 13240;
pub const EGL_KHR_DISPLAY_REFERENCE: u32 = 1;
pub const EGL_TRACK_REFERENCES_KHR: u32 = 13138;
pub const EGL_KHR_FENCE_SYNC: u32 = 1;
pub const EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR: u32 = 12528;
pub const EGL_SYNC_CONDITION_KHR: u32 = 12536;
pub const EGL_SYNC_FENCE_KHR: u32 = 12537;
pub const EGL_KHR_GET_ALL_PROC_ADDRESSES: u32 = 1;
pub const EGL_KHR_GL_COLORSPACE: u32 = 1;
pub const EGL_GL_COLORSPACE_KHR: u32 = 12445;
pub const EGL_GL_COLORSPACE_SRGB_KHR: u32 = 12425;
pub const EGL_GL_COLORSPACE_LINEAR_KHR: u32 = 12426;
pub const EGL_KHR_GL_RENDERBUFFER_IMAGE: u32 = 1;
pub const EGL_GL_RENDERBUFFER_KHR: u32 = 12473;
pub const EGL_KHR_GL_TEXTURE_2_D_IMAGE: u32 = 1;
pub const EGL_GL_TEXTURE_2D_KHR: u32 = 12465;
pub const EGL_GL_TEXTURE_LEVEL_KHR: u32 = 12476;
pub const EGL_KHR_GL_TEXTURE_3_D_IMAGE: u32 = 1;
pub const EGL_GL_TEXTURE_3D_KHR: u32 = 12466;
pub const EGL_GL_TEXTURE_ZOFFSET_KHR: u32 = 12477;
pub const EGL_KHR_GL_TEXTURE_CUBEMAP_IMAGE: u32 = 1;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR: u32 = 12467;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR: u32 = 12468;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR: u32 = 12469;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR: u32 = 12470;
pub const EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR: u32 = 12471;
pub const EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR: u32 = 12472;
pub const EGL_KHR_IMAGE: u32 = 1;
pub const EGL_NATIVE_PIXMAP_KHR: u32 = 12464;
pub const EGL_KHR_IMAGE_BASE: u32 = 1;
pub const EGL_IMAGE_PRESERVED_KHR: u32 = 12498;
pub const EGL_KHR_IMAGE_PIXMAP: u32 = 1;
pub const EGL_KHR_LOCK_SURFACE: u32 = 1;
pub const EGL_READ_SURFACE_BIT_KHR: u32 = 1;
pub const EGL_WRITE_SURFACE_BIT_KHR: u32 = 2;
pub const EGL_LOCK_SURFACE_BIT_KHR: u32 = 128;
pub const EGL_OPTIMAL_FORMAT_BIT_KHR: u32 = 256;
pub const EGL_MATCH_FORMAT_KHR: u32 = 12355;
pub const EGL_FORMAT_RGB_565_EXACT_KHR: u32 = 12480;
pub const EGL_FORMAT_RGB_565_KHR: u32 = 12481;
pub const EGL_FORMAT_RGBA_8888_EXACT_KHR: u32 = 12482;
pub const EGL_FORMAT_RGBA_8888_KHR: u32 = 12483;
pub const EGL_MAP_PRESERVE_PIXELS_KHR: u32 = 12484;
pub const EGL_LOCK_USAGE_HINT_KHR: u32 = 12485;
pub const EGL_BITMAP_POINTER_KHR: u32 = 12486;
pub const EGL_BITMAP_PITCH_KHR: u32 = 12487;
pub const EGL_BITMAP_ORIGIN_KHR: u32 = 12488;
pub const EGL_BITMAP_PIXEL_RED_OFFSET_KHR: u32 = 12489;
pub const EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR: u32 = 12490;
pub const EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR: u32 = 12491;
pub const EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR: u32 = 12492;
pub const EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR: u32 = 12493;
pub const EGL_LOWER_LEFT_KHR: u32 = 12494;
pub const EGL_UPPER_LEFT_KHR: u32 = 12495;
pub const EGL_KHR_LOCK_SURFACE2: u32 = 1;
pub const EGL_BITMAP_PIXEL_SIZE_KHR: u32 = 12560;
pub const EGL_KHR_LOCK_SURFACE3: u32 = 1;
pub const EGL_KHR_MUTABLE_RENDER_BUFFER: u32 = 1;
pub const EGL_MUTABLE_RENDER_BUFFER_BIT_KHR: u32 = 4096;
pub const EGL_KHR_NO_CONFIG_CONTEXT: u32 = 1;
pub const EGL_KHR_PARTIAL_UPDATE: u32 = 1;
pub const EGL_BUFFER_AGE_KHR: u32 = 12605;
pub const EGL_KHR_PLATFORM_ANDROID: u32 = 1;
pub const EGL_PLATFORM_ANDROID_KHR: u32 = 12609;
pub const EGL_KHR_PLATFORM_GBM: u32 = 1;
pub const EGL_PLATFORM_GBM_KHR: u32 = 12759;
pub const EGL_KHR_PLATFORM_WAYLAND: u32 = 1;
pub const EGL_PLATFORM_WAYLAND_KHR: u32 = 12760;
pub const EGL_KHR_PLATFORM_X11: u32 = 1;
pub const EGL_PLATFORM_X11_KHR: u32 = 12757;
pub const EGL_PLATFORM_X11_SCREEN_KHR: u32 = 12758;
pub const EGL_KHR_REUSABLE_SYNC: u32 = 1;
pub const EGL_SYNC_STATUS_KHR: u32 = 12529;
pub const EGL_SIGNALED_KHR: u32 = 12530;
pub const EGL_UNSIGNALED_KHR: u32 = 12531;
pub const EGL_TIMEOUT_EXPIRED_KHR: u32 = 12533;
pub const EGL_CONDITION_SATISFIED_KHR: u32 = 12534;
pub const EGL_SYNC_TYPE_KHR: u32 = 12535;
pub const EGL_SYNC_REUSABLE_KHR: u32 = 12538;
pub const EGL_SYNC_FLUSH_COMMANDS_BIT_KHR: u32 = 1;
pub const EGL_FOREVER_KHR: i32 = -1;
pub const EGL_KHR_STREAM: u32 = 1;
pub const EGL_CONSUMER_LATENCY_USEC_KHR: u32 = 12816;
pub const EGL_PRODUCER_FRAME_KHR: u32 = 12818;
pub const EGL_CONSUMER_FRAME_KHR: u32 = 12819;
pub const EGL_STREAM_STATE_KHR: u32 = 12820;
pub const EGL_STREAM_STATE_CREATED_KHR: u32 = 12821;
pub const EGL_STREAM_STATE_CONNECTING_KHR: u32 = 12822;
pub const EGL_STREAM_STATE_EMPTY_KHR: u32 = 12823;
pub const EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR: u32 = 12824;
pub const EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR: u32 = 12825;
pub const EGL_STREAM_STATE_DISCONNECTED_KHR: u32 = 12826;
pub const EGL_BAD_STREAM_KHR: u32 = 12827;
pub const EGL_BAD_STATE_KHR: u32 = 12828;
pub const EGL_KHR_STREAM_ATTRIB: u32 = 1;
pub const EGL_KHR_STREAM_CONSUMER_GLTEXTURE: u32 = 1;
pub const EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR: u32 = 12830;
pub const EGL_KHR_STREAM_CROSS_PROCESS_FD: u32 = 1;
pub const EGL_KHR_STREAM_FIFO: u32 = 1;
pub const EGL_STREAM_FIFO_LENGTH_KHR: u32 = 12796;
pub const EGL_STREAM_TIME_NOW_KHR: u32 = 12797;
pub const EGL_STREAM_TIME_CONSUMER_KHR: u32 = 12798;
pub const EGL_STREAM_TIME_PRODUCER_KHR: u32 = 12799;
pub const EGL_KHR_STREAM_PRODUCER_ALDATALOCATOR: u32 = 1;
pub const EGL_KHR_STREAM_PRODUCER_EGLSURFACE: u32 = 1;
pub const EGL_STREAM_BIT_KHR: u32 = 2048;
pub const EGL_KHR_SURFACELESS_CONTEXT: u32 = 1;
pub const EGL_KHR_SWAP_BUFFERS_WITH_DAMAGE: u32 = 1;
pub const EGL_KHR_VG_PARENT_IMAGE: u32 = 1;
pub const EGL_VG_PARENT_IMAGE_KHR: u32 = 12474;
pub const EGL_KHR_WAIT_SYNC: u32 = 1;
pub const EGL_ANDROID_GLES_LAYERS: u32 = 1;
pub const EGL_ANDROID_BLOB_CACHE: u32 = 1;
pub const EGL_ANDROID_CREATE_NATIVE_CLIENT_BUFFER: u32 = 1;
pub const EGL_NATIVE_BUFFER_USAGE_ANDROID: u32 = 12611;
pub const EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID: u32 = 1;
pub const EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID: u32 = 2;
pub const EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID: u32 = 4;
pub const EGL_ANDROID_FRAMEBUFFER_TARGET: u32 = 1;
pub const EGL_FRAMEBUFFER_TARGET_ANDROID: u32 = 12615;
pub const EGL_ANDROID_FRONT_BUFFER_AUTO_REFRESH: u32 = 1;
pub const EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID: u32 = 12620;
pub const EGL_ANDROID_GET_FRAME_TIMESTAMPS: u32 = 1;
pub const EGL_TIMESTAMPS_ANDROID: u32 = 13360;
pub const EGL_COMPOSITE_DEADLINE_ANDROID: u32 = 13361;
pub const EGL_COMPOSITE_INTERVAL_ANDROID: u32 = 13362;
pub const EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID: u32 = 13363;
pub const EGL_REQUESTED_PRESENT_TIME_ANDROID: u32 = 13364;
pub const EGL_RENDERING_COMPLETE_TIME_ANDROID: u32 = 13365;
pub const EGL_COMPOSITION_LATCH_TIME_ANDROID: u32 = 13366;
pub const EGL_FIRST_COMPOSITION_START_TIME_ANDROID: u32 = 13367;
pub const EGL_LAST_COMPOSITION_START_TIME_ANDROID: u32 = 13368;
pub const EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID: u32 = 13369;
pub const EGL_DISPLAY_PRESENT_TIME_ANDROID: u32 = 13370;
pub const EGL_DEQUEUE_READY_TIME_ANDROID: u32 = 13371;
pub const EGL_READS_DONE_TIME_ANDROID: u32 = 13372;
pub const EGL_ANDROID_GET_NATIVE_CLIENT_BUFFER: u32 = 1;
pub const EGL_ANDROID_IMAGE_NATIVE_BUFFER: u32 = 1;
pub const EGL_NATIVE_BUFFER_ANDROID: u32 = 12608;
pub const EGL_ANDROID_NATIVE_FENCE_SYNC: u32 = 1;
pub const EGL_SYNC_NATIVE_FENCE_ANDROID: u32 = 12612;
pub const EGL_SYNC_NATIVE_FENCE_FD_ANDROID: u32 = 12613;
pub const EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID: u32 = 12614;
pub const EGL_NO_NATIVE_FENCE_FD_ANDROID: i32 = -1;
pub const EGL_ANDROID_PRESENTATION_TIME: u32 = 1;
pub const EGL_ANDROID_RECORDABLE: u32 = 1;
pub const EGL_RECORDABLE_ANDROID: u32 = 12610;
pub const EGL_ANDROID_TELEMETRY_HINT: u32 = 1;
pub const EGL_TELEMETRY_HINT_ANDROID: u32 = 13680;
pub const EGL_ANGLE_D3D_SHARE_HANDLE_CLIENT_BUFFER: u32 = 1;
pub const EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE: u32 = 12800;
pub const EGL_ANGLE_DEVICE_D3D: u32 = 1;
pub const EGL_D3D9_DEVICE_ANGLE: u32 = 13216;
pub const EGL_D3D11_DEVICE_ANGLE: u32 = 13217;
pub const EGL_ANGLE_QUERY_SURFACE_POINTER: u32 = 1;
pub const EGL_ANGLE_SURFACE_D3D_TEXTURE_2D_SHARE_HANDLE: u32 = 1;
pub const EGL_ANGLE_SYNC_CONTROL_RATE: u32 = 1;
pub const EGL_ANGLE_WINDOW_FIXED_SIZE: u32 = 1;
pub const EGL_FIXED_SIZE_ANGLE: u32 = 12801;
pub const EGL_ARM_IMAGE_FORMAT: u32 = 1;
pub const EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM: u32 = 12935;
pub const EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM: u32 = 12936;
pub const EGL_ARM_IMPLICIT_EXTERNAL_SYNC: u32 = 1;
pub const EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM: u32 = 12938;
pub const EGL_ARM_PIXMAP_MULTISAMPLE_DISCARD: u32 = 1;
pub const EGL_DISCARD_SAMPLES_ARM: u32 = 12934;
pub const EGL_EXT_BIND_TO_FRONT: u32 = 1;
pub const EGL_FRONT_BUFFER_EXT: u32 = 13412;
pub const EGL_EXT_BUFFER_AGE: u32 = 1;
pub const EGL_BUFFER_AGE_EXT: u32 = 12605;
pub const EGL_EXT_CLIENT_EXTENSIONS: u32 = 1;
pub const EGL_EXT_CLIENT_SYNC: u32 = 1;
pub const EGL_SYNC_CLIENT_EXT: u32 = 13156;
pub const EGL_SYNC_CLIENT_SIGNAL_EXT: u32 = 13157;
pub const EGL_EXT_COMPOSITOR: u32 = 1;
pub const EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT: u32 = 13408;
pub const EGL_EXTERNAL_REF_ID_EXT: u32 = 13409;
pub const EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT: u32 = 13410;
pub const EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT: u32 = 13411;
pub const EGL_EXT_CONFIG_SELECT_GROUP: u32 = 1;
pub const EGL_CONFIG_SELECT_GROUP_EXT: u32 = 13504;
pub const EGL_EXT_CREATE_CONTEXT_ROBUSTNESS: u32 = 1;
pub const EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT: u32 = 12479;
pub const EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT: u32 = 12600;
pub const EGL_NO_RESET_NOTIFICATION_EXT: u32 = 12734;
pub const EGL_LOSE_CONTEXT_ON_RESET_EXT: u32 = 12735;
pub const EGL_EXT_DEVICE_BASE: u32 = 1;
pub const EGL_BAD_DEVICE_EXT: u32 = 12843;
pub const EGL_DEVICE_EXT: u32 = 12844;
pub const EGL_EXT_DEVICE_DRM: u32 = 1;
pub const EGL_DRM_DEVICE_FILE_EXT: u32 = 12851;
pub const EGL_DRM_MASTER_FD_EXT: u32 = 13116;
pub const EGL_EXT_DEVICE_DRM_RENDER_NODE: u32 = 1;
pub const EGL_DRM_RENDER_NODE_FILE_EXT: u32 = 13175;
pub const EGL_EXT_DEVICE_ENUMERATION: u32 = 1;
pub const EGL_EXT_DEVICE_OPENWF: u32 = 1;
pub const EGL_OPENWF_DEVICE_ID_EXT: u32 = 12855;
pub const EGL_OPENWF_DEVICE_EXT: u32 = 13117;
pub const EGL_EXT_DEVICE_PERSISTENT_ID: u32 = 1;
pub const EGL_DEVICE_UUID_EXT: u32 = 13148;
pub const EGL_DRIVER_UUID_EXT: u32 = 13149;
pub const EGL_DRIVER_NAME_EXT: u32 = 13150;
pub const EGL_EXT_DEVICE_QUERY: u32 = 1;
pub const EGL_EXT_DEVICE_QUERY_NAME: u32 = 1;
pub const EGL_RENDERER_EXT: u32 = 13151;
pub const EGL_EXT_DISPLAY_ALLOC: u32 = 1;
pub const EGL_ALLOC_NEW_DISPLAY_EXT: u32 = 13177;
pub const EGL_EXT_EXPLICIT_DEVICE: u32 = 1;
pub const EGL_EXT_GL_COLORSPACE_BT2020_HLG: u32 = 1;
pub const EGL_GL_COLORSPACE_BT2020_HLG_EXT: u32 = 13632;
pub const EGL_EXT_GL_COLORSPACE_BT2020_LINEAR: u32 = 1;
pub const EGL_GL_COLORSPACE_BT2020_LINEAR_EXT: u32 = 13119;
pub const EGL_EXT_GL_COLORSPACE_BT2020_PQ: u32 = 1;
pub const EGL_GL_COLORSPACE_BT2020_PQ_EXT: u32 = 13120;
pub const EGL_EXT_GL_COLORSPACE_DISPLAY_P3: u32 = 1;
pub const EGL_GL_COLORSPACE_DISPLAY_P3_EXT: u32 = 13155;
pub const EGL_EXT_GL_COLORSPACE_DISPLAY_P3_LINEAR: u32 = 1;
pub const EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT: u32 = 13154;
pub const EGL_EXT_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH: u32 = 1;
pub const EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT: u32 = 13456;
pub const EGL_EXT_GL_COLORSPACE_SCRGB: u32 = 1;
pub const EGL_GL_COLORSPACE_SCRGB_EXT: u32 = 13137;
pub const EGL_EXT_GL_COLORSPACE_SCRGB_LINEAR: u32 = 1;
pub const EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT: u32 = 13136;
pub const EGL_EXT_IMAGE_DMA_BUF_IMPORT: u32 = 1;
pub const EGL_LINUX_DMA_BUF_EXT: u32 = 12912;
pub const EGL_LINUX_DRM_FOURCC_EXT: u32 = 12913;
pub const EGL_DMA_BUF_PLANE0_FD_EXT: u32 = 12914;
pub const EGL_DMA_BUF_PLANE0_OFFSET_EXT: u32 = 12915;
pub const EGL_DMA_BUF_PLANE0_PITCH_EXT: u32 = 12916;
pub const EGL_DMA_BUF_PLANE1_FD_EXT: u32 = 12917;
pub const EGL_DMA_BUF_PLANE1_OFFSET_EXT: u32 = 12918;
pub const EGL_DMA_BUF_PLANE1_PITCH_EXT: u32 = 12919;
pub const EGL_DMA_BUF_PLANE2_FD_EXT: u32 = 12920;
pub const EGL_DMA_BUF_PLANE2_OFFSET_EXT: u32 = 12921;
pub const EGL_DMA_BUF_PLANE2_PITCH_EXT: u32 = 12922;
pub const EGL_YUV_COLOR_SPACE_HINT_EXT: u32 = 12923;
pub const EGL_SAMPLE_RANGE_HINT_EXT: u32 = 12924;
pub const EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT: u32 = 12925;
pub const EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT: u32 = 12926;
pub const EGL_ITU_REC601_EXT: u32 = 12927;
pub const EGL_ITU_REC709_EXT: u32 = 12928;
pub const EGL_ITU_REC2020_EXT: u32 = 12929;
pub const EGL_YUV_FULL_RANGE_EXT: u32 = 12930;
pub const EGL_YUV_NARROW_RANGE_EXT: u32 = 12931;
pub const EGL_YUV_CHROMA_SITING_0_EXT: u32 = 12932;
pub const EGL_YUV_CHROMA_SITING_0_5_EXT: u32 = 12933;
pub const EGL_EXT_IMAGE_DMA_BUF_IMPORT_MODIFIERS: u32 = 1;
pub const EGL_DMA_BUF_PLANE3_FD_EXT: u32 = 13376;
pub const EGL_DMA_BUF_PLANE3_OFFSET_EXT: u32 = 13377;
pub const EGL_DMA_BUF_PLANE3_PITCH_EXT: u32 = 13378;
pub const EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT: u32 = 13379;
pub const EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT: u32 = 13380;
pub const EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT: u32 = 13381;
pub const EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT: u32 = 13382;
pub const EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT: u32 = 13383;
pub const EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT: u32 = 13384;
pub const EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT: u32 = 13385;
pub const EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT: u32 = 13386;
pub const EGL_EXT_IMAGE_GL_COLORSPACE: u32 = 1;
pub const EGL_GL_COLORSPACE_DEFAULT_EXT: u32 = 12621;
pub const EGL_EXT_IMAGE_IMPLICIT_SYNC_CONTROL: u32 = 1;
pub const EGL_IMPORT_SYNC_TYPE_EXT: u32 = 13424;
pub const EGL_IMPORT_IMPLICIT_SYNC_EXT: u32 = 13425;
pub const EGL_IMPORT_EXPLICIT_SYNC_EXT: u32 = 13426;
pub const EGL_EXT_MULTIVIEW_WINDOW: u32 = 1;
pub const EGL_MULTIVIEW_VIEW_COUNT_EXT: u32 = 12596;
pub const EGL_EXT_OUTPUT_BASE: u32 = 1;
pub const EGL_BAD_OUTPUT_LAYER_EXT: u32 = 12845;
pub const EGL_BAD_OUTPUT_PORT_EXT: u32 = 12846;
pub const EGL_SWAP_INTERVAL_EXT: u32 = 12847;
pub const EGL_EXT_OUTPUT_DRM: u32 = 1;
pub const EGL_DRM_CRTC_EXT: u32 = 12852;
pub const EGL_DRM_PLANE_EXT: u32 = 12853;
pub const EGL_DRM_CONNECTOR_EXT: u32 = 12854;
pub const EGL_EXT_OUTPUT_OPENWF: u32 = 1;
pub const EGL_OPENWF_PIPELINE_ID_EXT: u32 = 12856;
pub const EGL_OPENWF_PORT_ID_EXT: u32 = 12857;
pub const EGL_EXT_PIXEL_FORMAT_FLOAT: u32 = 1;
pub const EGL_COLOR_COMPONENT_TYPE_EXT: u32 = 13113;
pub const EGL_COLOR_COMPONENT_TYPE_FIXED_EXT: u32 = 13114;
pub const EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT: u32 = 13115;
pub const EGL_EXT_PLATFORM_BASE: u32 = 1;
pub const EGL_EXT_PLATFORM_DEVICE: u32 = 1;
pub const EGL_PLATFORM_DEVICE_EXT: u32 = 12607;
pub const EGL_EXT_PLATFORM_WAYLAND: u32 = 1;
pub const EGL_PLATFORM_WAYLAND_EXT: u32 = 12760;
pub const EGL_EXT_PLATFORM_X11: u32 = 1;
pub const EGL_PLATFORM_X11_EXT: u32 = 12757;
pub const EGL_PLATFORM_X11_SCREEN_EXT: u32 = 12758;
pub const EGL_EXT_PLATFORM_XCB: u32 = 1;
pub const EGL_PLATFORM_XCB_EXT: u32 = 12764;
pub const EGL_PLATFORM_XCB_SCREEN_EXT: u32 = 12766;
pub const EGL_EXT_PRESENT_OPAQUE: u32 = 1;
pub const EGL_PRESENT_OPAQUE_EXT: u32 = 12767;
pub const EGL_EXT_PROTECTED_CONTENT: u32 = 1;
pub const EGL_PROTECTED_CONTENT_EXT: u32 = 12992;
pub const EGL_EXT_PROTECTED_SURFACE: u32 = 1;
pub const EGL_EXT_QUERY_RESET_NOTIFICATION_STRATEGY: u32 = 1;
pub const EGL_EXT_STREAM_CONSUMER_EGLOUTPUT: u32 = 1;
pub const EGL_EXT_SURFACE_CTA861_3_METADATA: u32 = 1;
pub const EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT: u32 = 13152;
pub const EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT: u32 = 13153;
pub const EGL_EXT_SURFACE_SMPTE2086_METADATA: u32 = 1;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT: u32 = 13121;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT: u32 = 13122;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT: u32 = 13123;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT: u32 = 13124;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT: u32 = 13125;
pub const EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT: u32 = 13126;
pub const EGL_SMPTE2086_WHITE_POINT_X_EXT: u32 = 13127;
pub const EGL_SMPTE2086_WHITE_POINT_Y_EXT: u32 = 13128;
pub const EGL_SMPTE2086_MAX_LUMINANCE_EXT: u32 = 13129;
pub const EGL_SMPTE2086_MIN_LUMINANCE_EXT: u32 = 13130;
pub const EGL_METADATA_SCALING_EXT: u32 = 50000;
pub const EGL_EXT_SURFACE_COMPRESSION: u32 = 1;
pub const EGL_SURFACE_COMPRESSION_EXT: u32 = 13488;
pub const EGL_SURFACE_COMPRESSION_PLANE1_EXT: u32 = 12942;
pub const EGL_SURFACE_COMPRESSION_PLANE2_EXT: u32 = 12943;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT: u32 = 13489;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT: u32 = 13490;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT: u32 = 13492;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT: u32 = 13493;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT: u32 = 13494;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT: u32 = 13495;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT: u32 = 13496;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT: u32 = 13497;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT: u32 = 13498;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT: u32 = 13499;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT: u32 = 13500;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT: u32 = 13501;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT: u32 = 13502;
pub const EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT: u32 = 13503;
pub const EGL_EXT_SWAP_BUFFERS_WITH_DAMAGE: u32 = 1;
pub const EGL_EXT_SYNC_REUSE: u32 = 1;
pub const EGL_EXT_YUV_SURFACE: u32 = 1;
pub const EGL_YUV_ORDER_EXT: u32 = 13057;
pub const EGL_YUV_NUMBER_OF_PLANES_EXT: u32 = 13073;
pub const EGL_YUV_SUBSAMPLE_EXT: u32 = 13074;
pub const EGL_YUV_DEPTH_RANGE_EXT: u32 = 13079;
pub const EGL_YUV_CSC_STANDARD_EXT: u32 = 13066;
pub const EGL_YUV_PLANE_BPP_EXT: u32 = 13082;
pub const EGL_YUV_BUFFER_EXT: u32 = 13056;
pub const EGL_YUV_ORDER_YUV_EXT: u32 = 13058;
pub const EGL_YUV_ORDER_YVU_EXT: u32 = 13059;
pub const EGL_YUV_ORDER_YUYV_EXT: u32 = 13060;
pub const EGL_YUV_ORDER_UYVY_EXT: u32 = 13061;
pub const EGL_YUV_ORDER_YVYU_EXT: u32 = 13062;
pub const EGL_YUV_ORDER_VYUY_EXT: u32 = 13063;
pub const EGL_YUV_ORDER_AYUV_EXT: u32 = 13064;
pub const EGL_YUV_SUBSAMPLE_4_2_0_EXT: u32 = 13075;
pub const EGL_YUV_SUBSAMPLE_4_2_2_EXT: u32 = 13076;
pub const EGL_YUV_SUBSAMPLE_4_4_4_EXT: u32 = 13077;
pub const EGL_YUV_DEPTH_RANGE_LIMITED_EXT: u32 = 13080;
pub const EGL_YUV_DEPTH_RANGE_FULL_EXT: u32 = 13081;
pub const EGL_YUV_CSC_STANDARD_601_EXT: u32 = 13067;
pub const EGL_YUV_CSC_STANDARD_709_EXT: u32 = 13068;
pub const EGL_YUV_CSC_STANDARD_2020_EXT: u32 = 13069;
pub const EGL_YUV_PLANE_BPP_0_EXT: u32 = 13083;
pub const EGL_YUV_PLANE_BPP_8_EXT: u32 = 13084;
pub const EGL_YUV_PLANE_BPP_10_EXT: u32 = 13085;
pub const EGL_HI_CLIENTPIXMAP: u32 = 1;
pub const EGL_CLIENT_PIXMAP_POINTER_HI: u32 = 36724;
pub const EGL_HI_COLORFORMATS: u32 = 1;
pub const EGL_COLOR_FORMAT_HI: u32 = 36720;
pub const EGL_COLOR_RGB_HI: u32 = 36721;
pub const EGL_COLOR_RGBA_HI: u32 = 36722;
pub const EGL_COLOR_ARGB_HI: u32 = 36723;
pub const EGL_IMG_CONTEXT_PRIORITY: u32 = 1;
pub const EGL_CONTEXT_PRIORITY_LEVEL_IMG: u32 = 12544;
pub const EGL_CONTEXT_PRIORITY_HIGH_IMG: u32 = 12545;
pub const EGL_CONTEXT_PRIORITY_MEDIUM_IMG: u32 = 12546;
pub const EGL_CONTEXT_PRIORITY_LOW_IMG: u32 = 12547;
pub const EGL_IMG_IMAGE_PLANE_ATTRIBS: u32 = 1;
pub const EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG: u32 = 12549;
pub const EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG: u32 = 12550;
pub const EGL_MESA_DRM_IMAGE: u32 = 1;
pub const EGL_DRM_BUFFER_FORMAT_MESA: u32 = 12752;
pub const EGL_DRM_BUFFER_USE_MESA: u32 = 12753;
pub const EGL_DRM_BUFFER_FORMAT_ARGB32_MESA: u32 = 12754;
pub const EGL_DRM_BUFFER_MESA: u32 = 12755;
pub const EGL_DRM_BUFFER_STRIDE_MESA: u32 = 12756;
pub const EGL_DRM_BUFFER_USE_SCANOUT_MESA: u32 = 1;
pub const EGL_DRM_BUFFER_USE_SHARE_MESA: u32 = 2;
pub const EGL_DRM_BUFFER_USE_CURSOR_MESA: u32 = 4;
pub const EGL_MESA_IMAGE_DMA_BUF_EXPORT: u32 = 1;
pub const EGL_MESA_PLATFORM_GBM: u32 = 1;
pub const EGL_PLATFORM_GBM_MESA: u32 = 12759;
pub const EGL_MESA_PLATFORM_SURFACELESS: u32 = 1;
pub const EGL_PLATFORM_SURFACELESS_MESA: u32 = 12765;
pub const EGL_MESA_QUERY_DRIVER: u32 = 1;
pub const EGL_NOK_SWAP_REGION: u32 = 1;
pub const EGL_NOK_SWAP_REGION2: u32 = 1;
pub const EGL_NOK_TEXTURE_FROM_PIXMAP: u32 = 1;
pub const EGL_Y_INVERTED_NOK: u32 = 12415;
pub const EGL_NV_3DVISION_SURFACE: u32 = 1;
pub const EGL_AUTO_STEREO_NV: u32 = 12598;
pub const EGL_NV_CONTEXT_PRIORITY_REALTIME: u32 = 1;
pub const EGL_CONTEXT_PRIORITY_REALTIME_NV: u32 = 13143;
pub const EGL_NV_COVERAGE_SAMPLE: u32 = 1;
pub const EGL_COVERAGE_BUFFERS_NV: u32 = 12512;
pub const EGL_COVERAGE_SAMPLES_NV: u32 = 12513;
pub const EGL_NV_COVERAGE_SAMPLE_RESOLVE: u32 = 1;
pub const EGL_COVERAGE_SAMPLE_RESOLVE_NV: u32 = 12593;
pub const EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV: u32 = 12594;
pub const EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV: u32 = 12595;
pub const EGL_NV_CUDA_EVENT: u32 = 1;
pub const EGL_CUDA_EVENT_HANDLE_NV: u32 = 12859;
pub const EGL_SYNC_CUDA_EVENT_NV: u32 = 12860;
pub const EGL_SYNC_CUDA_EVENT_COMPLETE_NV: u32 = 12861;
pub const EGL_NV_DEPTH_NONLINEAR: u32 = 1;
pub const EGL_DEPTH_ENCODING_NV: u32 = 12514;
pub const EGL_DEPTH_ENCODING_NONE_NV: u32 = 0;
pub const EGL_DEPTH_ENCODING_NONLINEAR_NV: u32 = 12515;
pub const EGL_NV_DEVICE_CUDA: u32 = 1;
pub const EGL_CUDA_DEVICE_NV: u32 = 12858;
pub const EGL_NV_NATIVE_QUERY: u32 = 1;
pub const EGL_NV_POST_CONVERT_ROUNDING: u32 = 1;
pub const EGL_NV_POST_SUB_BUFFER: u32 = 1;
pub const EGL_POST_SUB_BUFFER_SUPPORTED_NV: u32 = 12478;
pub const EGL_NV_QUADRUPLE_BUFFER: u32 = 1;
pub const EGL_QUADRUPLE_BUFFER_NV: u32 = 12849;
pub const EGL_NV_ROBUSTNESS_VIDEO_MEMORY_PURGE: u32 = 1;
pub const EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV: u32 = 13132;
pub const EGL_NV_STREAM_CONSUMER_EGLIMAGE: u32 = 1;
pub const EGL_STREAM_CONSUMER_IMAGE_NV: u32 = 13171;
pub const EGL_STREAM_IMAGE_ADD_NV: u32 = 13172;
pub const EGL_STREAM_IMAGE_REMOVE_NV: u32 = 13173;
pub const EGL_STREAM_IMAGE_AVAILABLE_NV: u32 = 13174;
pub const EGL_NV_STREAM_CONSUMER_EGLIMAGE_USE_SCANOUT_ATTRIB: u32 = 1;
pub const EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV: u32 = 13176;
pub const EGL_NV_STREAM_CONSUMER_GLTEXTURE_YUV: u32 = 1;
pub const EGL_YUV_PLANE0_TEXTURE_UNIT_NV: u32 = 13100;
pub const EGL_YUV_PLANE1_TEXTURE_UNIT_NV: u32 = 13101;
pub const EGL_YUV_PLANE2_TEXTURE_UNIT_NV: u32 = 13102;
pub const EGL_NV_STREAM_CROSS_DISPLAY: u32 = 1;
pub const EGL_STREAM_CROSS_DISPLAY_NV: u32 = 13134;
pub const EGL_NV_STREAM_CROSS_OBJECT: u32 = 1;
pub const EGL_STREAM_CROSS_OBJECT_NV: u32 = 13133;
pub const EGL_NV_STREAM_CROSS_PARTITION: u32 = 1;
pub const EGL_STREAM_CROSS_PARTITION_NV: u32 = 12863;
pub const EGL_NV_STREAM_CROSS_PROCESS: u32 = 1;
pub const EGL_STREAM_CROSS_PROCESS_NV: u32 = 12869;
pub const EGL_NV_STREAM_CROSS_SYSTEM: u32 = 1;
pub const EGL_STREAM_CROSS_SYSTEM_NV: u32 = 13135;
pub const EGL_NV_STREAM_DMA: u32 = 1;
pub const EGL_STREAM_DMA_NV: u32 = 13169;
pub const EGL_STREAM_DMA_SERVER_NV: u32 = 13170;
pub const EGL_NV_STREAM_FIFO_NEXT: u32 = 1;
pub const EGL_PENDING_FRAME_NV: u32 = 13097;
pub const EGL_STREAM_TIME_PENDING_NV: u32 = 13098;
pub const EGL_NV_STREAM_FIFO_SYNCHRONOUS: u32 = 1;
pub const EGL_STREAM_FIFO_SYNCHRONOUS_NV: u32 = 13110;
pub const EGL_NV_STREAM_FLUSH: u32 = 1;
pub const EGL_NV_STREAM_FRAME_LIMITS: u32 = 1;
pub const EGL_PRODUCER_MAX_FRAME_HINT_NV: u32 = 13111;
pub const EGL_CONSUMER_MAX_FRAME_HINT_NV: u32 = 13112;
pub const EGL_NV_STREAM_METADATA: u32 = 1;
pub const EGL_MAX_STREAM_METADATA_BLOCKS_NV: u32 = 12880;
pub const EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV: u32 = 12881;
pub const EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV: u32 = 12882;
pub const EGL_PRODUCER_METADATA_NV: u32 = 12883;
pub const EGL_CONSUMER_METADATA_NV: u32 = 12884;
pub const EGL_PENDING_METADATA_NV: u32 = 13096;
pub const EGL_METADATA0_SIZE_NV: u32 = 12885;
pub const EGL_METADATA1_SIZE_NV: u32 = 12886;
pub const EGL_METADATA2_SIZE_NV: u32 = 12887;
pub const EGL_METADATA3_SIZE_NV: u32 = 12888;
pub const EGL_METADATA0_TYPE_NV: u32 = 12889;
pub const EGL_METADATA1_TYPE_NV: u32 = 12890;
pub const EGL_METADATA2_TYPE_NV: u32 = 12891;
pub const EGL_METADATA3_TYPE_NV: u32 = 12892;
pub const EGL_NV_STREAM_ORIGIN: u32 = 1;
pub const EGL_STREAM_FRAME_ORIGIN_X_NV: u32 = 13158;
pub const EGL_STREAM_FRAME_ORIGIN_Y_NV: u32 = 13159;
pub const EGL_STREAM_FRAME_MAJOR_AXIS_NV: u32 = 13160;
pub const EGL_CONSUMER_AUTO_ORIENTATION_NV: u32 = 13161;
pub const EGL_PRODUCER_AUTO_ORIENTATION_NV: u32 = 13162;
pub const EGL_LEFT_NV: u32 = 13163;
pub const EGL_RIGHT_NV: u32 = 13164;
pub const EGL_TOP_NV: u32 = 13165;
pub const EGL_BOTTOM_NV: u32 = 13166;
pub const EGL_X_AXIS_NV: u32 = 13167;
pub const EGL_Y_AXIS_NV: u32 = 13168;
pub const EGL_NV_STREAM_REMOTE: u32 = 1;
pub const EGL_STREAM_STATE_INITIALIZING_NV: u32 = 12864;
pub const EGL_STREAM_TYPE_NV: u32 = 12865;
pub const EGL_STREAM_PROTOCOL_NV: u32 = 12866;
pub const EGL_STREAM_ENDPOINT_NV: u32 = 12867;
pub const EGL_STREAM_LOCAL_NV: u32 = 12868;
pub const EGL_STREAM_PRODUCER_NV: u32 = 12871;
pub const EGL_STREAM_CONSUMER_NV: u32 = 12872;
pub const EGL_STREAM_PROTOCOL_FD_NV: u32 = 12870;
pub const EGL_NV_STREAM_RESET: u32 = 1;
pub const EGL_SUPPORT_RESET_NV: u32 = 13108;
pub const EGL_SUPPORT_REUSE_NV: u32 = 13109;
pub const EGL_NV_STREAM_SOCKET: u32 = 1;
pub const EGL_STREAM_PROTOCOL_SOCKET_NV: u32 = 12875;
pub const EGL_SOCKET_HANDLE_NV: u32 = 12876;
pub const EGL_SOCKET_TYPE_NV: u32 = 12877;
pub const EGL_NV_STREAM_SOCKET_INET: u32 = 1;
pub const EGL_SOCKET_TYPE_INET_NV: u32 = 12879;
pub const EGL_NV_STREAM_SOCKET_UNIX: u32 = 1;
pub const EGL_SOCKET_TYPE_UNIX_NV: u32 = 12878;
pub const EGL_NV_STREAM_SYNC: u32 = 1;
pub const EGL_SYNC_NEW_FRAME_NV: u32 = 12831;
pub const EGL_NV_SYNC: u32 = 1;
pub const EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV: u32 = 12518;
pub const EGL_SYNC_STATUS_NV: u32 = 12519;
pub const EGL_SIGNALED_NV: u32 = 12520;
pub const EGL_UNSIGNALED_NV: u32 = 12521;
pub const EGL_SYNC_FLUSH_COMMANDS_BIT_NV: u32 = 1;
pub const EGL_FOREVER_NV: i32 = -1;
pub const EGL_ALREADY_SIGNALED_NV: u32 = 12522;
pub const EGL_TIMEOUT_EXPIRED_NV: u32 = 12523;
pub const EGL_CONDITION_SATISFIED_NV: u32 = 12524;
pub const EGL_SYNC_TYPE_NV: u32 = 12525;
pub const EGL_SYNC_CONDITION_NV: u32 = 12526;
pub const EGL_SYNC_FENCE_NV: u32 = 12527;
pub const EGL_NV_SYSTEM_TIME: u32 = 1;
pub const EGL_NV_TRIPLE_BUFFER: u32 = 1;
pub const EGL_TRIPLE_BUFFER_NV: u32 = 12848;
pub const EGL_QNX_IMAGE_NATIVE_BUFFER: u32 = 1;
pub const EGL_NATIVE_BUFFER_QNX: u32 = 13649;
pub const EGL_QNX_PLATFORM_SCREEN: u32 = 1;
pub const EGL_PLATFORM_SCREEN_QNX: u32 = 13648;
pub const EGL_TIZEN_IMAGE_NATIVE_BUFFER: u32 = 1;
pub const EGL_NATIVE_BUFFER_TIZEN: u32 = 12960;
pub const EGL_TIZEN_IMAGE_NATIVE_SURFACE: u32 = 1;
pub const EGL_NATIVE_SURFACE_TIZEN: u32 = 12961;
pub const EGL_WL_BIND_WAYLAND_DISPLAY: u32 = 1;
pub const EGL_WAYLAND_BUFFER_WL: u32 = 12757;
pub const EGL_WAYLAND_PLANE_WL: u32 = 12758;
pub const EGL_TEXTURE_Y_U_V_WL: u32 = 12759;
pub const EGL_TEXTURE_Y_UV_WL: u32 = 12760;
pub const EGL_TEXTURE_Y_XUXV_WL: u32 = 12761;
pub const EGL_TEXTURE_EXTERNAL_WL: u32 = 12762;
pub const EGL_WAYLAND_Y_INVERTED_WL: u32 = 12763;
pub const EGL_WL_CREATE_WAYLAND_BUFFER_FROM_IMAGE: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type khronos_int32_t = i32;
pub type khronos_uint32_t = u32;
pub type khronos_int64_t = i64;
pub type khronos_uint64_t = u64;
pub type khronos_int8_t = ::std::os::raw::c_schar;
pub type khronos_uint8_t = ::std::os::raw::c_uchar;
pub type khronos_int16_t = ::std::os::raw::c_short;
pub type khronos_uint16_t = ::std::os::raw::c_ushort;
pub type khronos_intptr_t = ::std::os::raw::c_long;
pub type khronos_uintptr_t = ::std::os::raw::c_ulong;
pub type khronos_ssize_t = ::std::os::raw::c_long;
pub type khronos_usize_t = ::std::os::raw::c_ulong;
pub type khronos_float_t = f32;
pub type khronos_utime_nanoseconds_t = khronos_uint64_t;
pub type khronos_stime_nanoseconds_t = khronos_int64_t;
pub const KHRONOS_BOOLEAN_ENUM_T_KHRONOS_FALSE: khronos_boolean_enum_t = 0;
pub const KHRONOS_BOOLEAN_ENUM_T_KHRONOS_TRUE: khronos_boolean_enum_t = 1;
pub const KHRONOS_BOOLEAN_ENUM_T_KHRONOS_BOOLEAN_ENUM_FORCE_SIZE: khronos_boolean_enum_t =
    2147483647;
pub type khronos_boolean_enum_t = ::std::os::raw::c_uint;
pub type EGLNativeDisplayType = *mut ::std::os::raw::c_void;
pub type EGLNativePixmapType = khronos_uintptr_t;
pub type EGLNativeWindowType = khronos_uintptr_t;
pub type NativeDisplayType = EGLNativeDisplayType;
pub type NativePixmapType = EGLNativePixmapType;
pub type NativeWindowType = EGLNativeWindowType;
pub type EGLint = khronos_int32_t;
pub type EGLBoolean = ::std::os::raw::c_uint;
pub type EGLDisplay = *mut ::std::os::raw::c_void;
pub type EGLConfig = *mut ::std::os::raw::c_void;
pub type EGLSurface = *mut ::std::os::raw::c_void;
pub type EGLContext = *mut ::std::os::raw::c_void;
pub type __eglMustCastToProperFunctionPointerType = ::std::option::Option<unsafe extern "C" fn()>;
pub type PFNEGLCHOOSECONFIGPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        attrib_list: *const EGLint,
        configs: *mut EGLConfig,
        config_size: EGLint,
        num_config: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLCOPYBUFFERSPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        target: EGLNativePixmapType,
    ) -> EGLBoolean,
>;
pub type PFNEGLCREATECONTEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        share_context: EGLContext,
        attrib_list: *const EGLint,
    ) -> EGLContext,
>;
pub type PFNEGLCREATEPBUFFERSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLCREATEPIXMAPSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        pixmap: EGLNativePixmapType,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLCREATEWINDOWSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        win: EGLNativeWindowType,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLDESTROYCONTEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, ctx: EGLContext) -> EGLBoolean>;
pub type PFNEGLDESTROYSURFACEPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface) -> EGLBoolean>;
pub type PFNEGLGETCONFIGATTRIBPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        attribute: EGLint,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETCONFIGSPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        configs: *mut EGLConfig,
        config_size: EGLint,
        num_config: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETCURRENTDISPLAYPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLDisplay>;
pub type PFNEGLGETCURRENTSURFACEPROC =
    ::std::option::Option<unsafe extern "C" fn(readdraw: EGLint) -> EGLSurface>;
pub type PFNEGLGETDISPLAYPROC =
    ::std::option::Option<unsafe extern "C" fn(display_id: EGLNativeDisplayType) -> EGLDisplay>;
pub type PFNEGLGETERRORPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLint>;
pub type PFNEGLGETPROCADDRESSPROC = ::std::option::Option<
    unsafe extern "C" fn(
        procname: *const ::std::os::raw::c_char,
    ) -> __eglMustCastToProperFunctionPointerType,
>;
pub type PFNEGLINITIALIZEPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, major: *mut EGLint, minor: *mut EGLint) -> EGLBoolean,
>;
pub type PFNEGLMAKECURRENTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        draw: EGLSurface,
        read: EGLSurface,
        ctx: EGLContext,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYCONTEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        ctx: EGLContext,
        attribute: EGLint,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTRINGPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, name: EGLint) -> *const ::std::os::raw::c_char,
>;
pub type PFNEGLQUERYSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        attribute: EGLint,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSWAPBUFFERSPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface) -> EGLBoolean>;
pub type PFNEGLTERMINATEPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay) -> EGLBoolean>;
pub type PFNEGLWAITGLPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLBoolean>;
pub type PFNEGLWAITNATIVEPROC =
    ::std::option::Option<unsafe extern "C" fn(engine: EGLint) -> EGLBoolean>;

pub type PFNEGLBINDTEXIMAGEPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface, buffer: EGLint) -> EGLBoolean,
>;
pub type PFNEGLRELEASETEXIMAGEPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface, buffer: EGLint) -> EGLBoolean,
>;
pub type PFNEGLSURFACEATTRIBPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        attribute: EGLint,
        value: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSWAPINTERVALPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, interval: EGLint) -> EGLBoolean>;

pub type EGLenum = ::std::os::raw::c_uint;
pub type EGLClientBuffer = *mut ::std::os::raw::c_void;
pub type PFNEGLBINDAPIPROC =
    ::std::option::Option<unsafe extern "C" fn(api: EGLenum) -> EGLBoolean>;
pub type PFNEGLQUERYAPIPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLenum>;
pub type PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        buftype: EGLenum,
        buffer: EGLClientBuffer,
        config: EGLConfig,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLRELEASETHREADPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLBoolean>;
pub type PFNEGLWAITCLIENTPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLBoolean>;

pub type PFNEGLGETCURRENTCONTEXTPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLContext>;
pub type EGLSync = *mut ::std::os::raw::c_void;
pub type EGLAttrib = isize;
pub type EGLTime = khronos_utime_nanoseconds_t;
pub type EGLImage = *mut ::std::os::raw::c_void;
pub type PFNEGLCREATESYNCPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, type_: EGLenum, attrib_list: *const EGLAttrib) -> EGLSync,
>;
pub type PFNEGLDESTROYSYNCPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSync) -> EGLBoolean>;
pub type PFNEGLCLIENTWAITSYNCPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSync, flags: EGLint, timeout: EGLTime) -> EGLint,
>;
pub type PFNEGLGETSYNCATTRIBPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        sync: EGLSync,
        attribute: EGLint,
        value: *mut EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLCREATEIMAGEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        ctx: EGLContext,
        target: EGLenum,
        buffer: EGLClientBuffer,
        attrib_list: *const EGLAttrib,
    ) -> EGLImage,
>;
pub type PFNEGLDESTROYIMAGEPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, image: EGLImage) -> EGLBoolean>;
pub type PFNEGLGETPLATFORMDISPLAYPROC = ::std::option::Option<
    unsafe extern "C" fn(
        platform: EGLenum,
        native_display: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLAttrib,
    ) -> EGLDisplay,
>;
pub type PFNEGLCREATEPLATFORMWINDOWSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        native_window: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLAttrib,
    ) -> EGLSurface,
>;
pub type PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        native_pixmap: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLAttrib,
    ) -> EGLSurface,
>;
pub type PFNEGLWAITSYNCPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSync, flags: EGLint) -> EGLBoolean,
>;

pub type EGLSyncKHR = *mut ::std::os::raw::c_void;
pub type EGLAttribKHR = isize;
pub type PFNEGLCREATESYNC64KHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        type_: EGLenum,
        attrib_list: *const EGLAttribKHR,
    ) -> EGLSyncKHR,
>;
pub type EGLLabelKHR = *mut ::std::os::raw::c_void;
pub type EGLObjectKHR = *mut ::std::os::raw::c_void;
pub type EGLDEBUGPROCKHR = ::std::option::Option<
    unsafe extern "C" fn(
        error: EGLenum,
        command: *const ::std::os::raw::c_char,
        messageType: EGLint,
        threadLabel: EGLLabelKHR,
        objectLabel: EGLLabelKHR,
        message: *const ::std::os::raw::c_char,
    ),
>;
pub type PFNEGLDEBUGMESSAGECONTROLKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(callback: EGLDEBUGPROCKHR, attrib_list: *const EGLAttrib) -> EGLint,
>;
pub type PFNEGLQUERYDEBUGKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(attribute: EGLint, value: *mut EGLAttrib) -> EGLBoolean,
>;
pub type PFNEGLLABELOBJECTKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        display: EGLDisplay,
        objectType: EGLenum,
        object: EGLObjectKHR,
        label: EGLLabelKHR,
    ) -> EGLint,
>;
pub type PFNEGLQUERYDISPLAYATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, name: EGLint, value: *mut EGLAttrib) -> EGLBoolean,
>;
pub type EGLTimeKHR = khronos_utime_nanoseconds_t;
pub type PFNEGLCREATESYNCKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, type_: EGLenum, attrib_list: *const EGLint) -> EGLSyncKHR,
>;
pub type PFNEGLDESTROYSYNCKHRPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSyncKHR) -> EGLBoolean>;
pub type PFNEGLCLIENTWAITSYNCKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        sync: EGLSyncKHR,
        flags: EGLint,
        timeout: EGLTimeKHR,
    ) -> EGLint,
>;
pub type PFNEGLGETSYNCATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        sync: EGLSyncKHR,
        attribute: EGLint,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type EGLImageKHR = *mut ::std::os::raw::c_void;
pub type PFNEGLCREATEIMAGEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        ctx: EGLContext,
        target: EGLenum,
        buffer: EGLClientBuffer,
        attrib_list: *const EGLint,
    ) -> EGLImageKHR,
>;
pub type PFNEGLDESTROYIMAGEKHRPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, image: EGLImageKHR) -> EGLBoolean>;
pub type PFNEGLLOCKSURFACEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        attrib_list: *const EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLUNLOCKSURFACEKHRPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface) -> EGLBoolean>;
pub type PFNEGLQUERYSURFACE64KHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        attribute: EGLint,
        value: *mut EGLAttribKHR,
    ) -> EGLBoolean,
>;
pub type PFNEGLSETDAMAGEREGIONKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        rects: *mut EGLint,
        n_rects: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSIGNALSYNCKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSyncKHR, mode: EGLenum) -> EGLBoolean,
>;
pub type EGLStreamKHR = *mut ::std::os::raw::c_void;
pub type EGLuint64KHR = khronos_uint64_t;
pub type PFNEGLCREATESTREAMKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, attrib_list: *const EGLint) -> EGLStreamKHR,
>;
pub type PFNEGLDESTROYSTREAMKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type PFNEGLSTREAMATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTREAMKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTREAMU64KHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: *mut EGLuint64KHR,
    ) -> EGLBoolean,
>;
pub type PFNEGLCREATESTREAMATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, attrib_list: *const EGLAttrib) -> EGLStreamKHR,
>;
pub type PFNEGLSETSTREAMATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTREAMATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: *mut EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERACQUIREKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERRELEASEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type EGLNativeFileDescriptorKHR = ::std::os::raw::c_int;
pub type PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLNativeFileDescriptorKHR,
>;
pub type PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        file_descriptor: EGLNativeFileDescriptorKHR,
    ) -> EGLStreamKHR,
>;
pub type PFNEGLQUERYSTREAMTIMEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attribute: EGLenum,
        value: *mut EGLTimeKHR,
    ) -> EGLBoolean,
>;
pub type PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        stream: EGLStreamKHR,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        rects: *const EGLint,
        n_rects: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLWAITSYNCKHRPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSyncKHR, flags: EGLint) -> EGLint,
>;
pub type EGLsizeiANDROID = khronos_ssize_t;
pub type EGLSetBlobFuncANDROID = ::std::option::Option<
    unsafe extern "C" fn(
        key: *const ::std::os::raw::c_void,
        keySize: EGLsizeiANDROID,
        value: *const ::std::os::raw::c_void,
        valueSize: EGLsizeiANDROID,
    ),
>;
pub type EGLGetBlobFuncANDROID = ::std::option::Option<
    unsafe extern "C" fn(
        key: *const ::std::os::raw::c_void,
        keySize: EGLsizeiANDROID,
        value: *mut ::std::os::raw::c_void,
        valueSize: EGLsizeiANDROID,
    ) -> EGLsizeiANDROID,
>;
pub type PFNEGLSETBLOBCACHEFUNCSANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, set: EGLSetBlobFuncANDROID, get: EGLGetBlobFuncANDROID),
>;
pub type PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC =
    ::std::option::Option<unsafe extern "C" fn(attrib_list: *const EGLint) -> EGLClientBuffer>;
pub type EGLnsecsANDROID = khronos_stime_nanoseconds_t;
pub type PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface, name: EGLint) -> EGLBoolean,
>;
pub type PFNEGLGETCOMPOSITORTIMINGANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        numTimestamps: EGLint,
        names: *const EGLint,
        values: *mut EGLnsecsANDROID,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETNEXTFRAMEIDANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        frameId: *mut EGLuint64KHR,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface, timestamp: EGLint) -> EGLBoolean,
>;
pub type PFNEGLGETFRAMETIMESTAMPSANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        frameId: EGLuint64KHR,
        numTimestamps: EGLint,
        timestamps: *const EGLint,
        values: *mut EGLnsecsANDROID,
    ) -> EGLBoolean,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AHardwareBuffer {
    _unused: [u8; 0],
}
pub type PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC =
    ::std::option::Option<unsafe extern "C" fn(buffer: *const AHardwareBuffer) -> EGLClientBuffer>;
pub type PFNEGLDUPNATIVEFENCEFDANDROIDPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay, sync: EGLSyncKHR) -> EGLint>;
pub type PFNEGLPRESENTATIONTIMEANDROIDPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, surface: EGLSurface, time: EGLnsecsANDROID) -> EGLBoolean,
>;
pub type PFNEGLQUERYSURFACEPOINTERANGLEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        attribute: EGLint,
        value: *mut *mut ::std::os::raw::c_void,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETMSCRATEANGLEPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        numerator: *mut EGLint,
        denominator: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLCLIENTSIGNALSYNCEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        sync: EGLSync,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(external_ref_ids: *const EGLint, num_entries: EGLint) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        external_ref_id: EGLint,
        context_attributes: *const EGLint,
        num_entries: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        external_ref_id: EGLint,
        external_win_ids: *const EGLint,
        num_entries: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        external_win_id: EGLint,
        window_attributes: *const EGLint,
        num_entries: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(external_win_id: EGLint) -> EGLBoolean>;
pub type PFNEGLCOMPOSITORSETSIZEEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(external_win_id: EGLint, width: EGLint, height: EGLint) -> EGLBoolean,
>;
pub type PFNEGLCOMPOSITORSWAPPOLICYEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(external_win_id: EGLint, policy: EGLint) -> EGLBoolean,
>;
pub type EGLDeviceEXT = *mut ::std::os::raw::c_void;
pub type PFNEGLQUERYDEVICEATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        device: EGLDeviceEXT,
        attribute: EGLint,
        value: *mut EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYDEVICESTRINGEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(device: EGLDeviceEXT, name: EGLint) -> *const ::std::os::raw::c_char,
>;
pub type PFNEGLQUERYDEVICESEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        max_devices: EGLint,
        devices: *mut EGLDeviceEXT,
        num_devices: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYDISPLAYATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, attribute: EGLint, value: *mut EGLAttrib) -> EGLBoolean,
>;
pub type PFNEGLQUERYDEVICEBINARYEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        device: EGLDeviceEXT,
        name: EGLint,
        max_size: EGLint,
        value: *mut ::std::os::raw::c_void,
        size: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLDESTROYDISPLAYEXTPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay) -> EGLBoolean>;
pub type PFNEGLQUERYDMABUFFORMATSEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        max_formats: EGLint,
        formats: *mut EGLint,
        num_formats: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYDMABUFMODIFIERSEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        format: EGLint,
        max_modifiers: EGLint,
        modifiers: *mut EGLuint64KHR,
        external_only: *mut EGLBoolean,
        num_modifiers: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type EGLOutputLayerEXT = *mut ::std::os::raw::c_void;
pub type EGLOutputPortEXT = *mut ::std::os::raw::c_void;
pub type PFNEGLGETOUTPUTLAYERSEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        attrib_list: *const EGLAttrib,
        layers: *mut EGLOutputLayerEXT,
        max_layers: EGLint,
        num_layers: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETOUTPUTPORTSEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        attrib_list: *const EGLAttrib,
        ports: *mut EGLOutputPortEXT,
        max_ports: EGLint,
        num_ports: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLOUTPUTLAYERATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        layer: EGLOutputLayerEXT,
        attribute: EGLint,
        value: EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        layer: EGLOutputLayerEXT,
        attribute: EGLint,
        value: *mut EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        layer: EGLOutputLayerEXT,
        name: EGLint,
    ) -> *const ::std::os::raw::c_char,
>;
pub type PFNEGLOUTPUTPORTATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        port: EGLOutputPortEXT,
        attribute: EGLint,
        value: EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        port: EGLOutputPortEXT,
        attribute: EGLint,
        value: *mut EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        port: EGLOutputPortEXT,
        name: EGLint,
    ) -> *const ::std::os::raw::c_char,
>;
pub type PFNEGLGETPLATFORMDISPLAYEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        platform: EGLenum,
        native_display: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLint,
    ) -> EGLDisplay,
>;
pub type PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        native_window: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        native_pixmap: *mut ::std::os::raw::c_void,
        attrib_list: *const EGLint,
    ) -> EGLSurface,
>;
pub type PFNEGLSTREAMCONSUMEROUTPUTEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        layer: EGLOutputLayerEXT,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        attrib_list: *const EGLAttrib,
        rates: *mut EGLint,
        rate_size: EGLint,
        num_rates: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        rects: *const EGLint,
        n_rects: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLUNSIGNALSYNCEXTPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        sync: EGLSync,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct EGLClientPixmapHI {
    pub pData: *mut ::std::os::raw::c_void,
    pub iWidth: EGLint,
    pub iHeight: EGLint,
    pub iStride: EGLint,
}
pub type PFNEGLCREATEPIXMAPSURFACEHIPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        config: EGLConfig,
        pixmap: *mut EGLClientPixmapHI,
    ) -> EGLSurface,
>;
pub type PFNEGLCREATEDRMIMAGEMESAPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, attrib_list: *const EGLint) -> EGLImageKHR,
>;
pub type PFNEGLEXPORTDRMIMAGEMESAPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        image: EGLImageKHR,
        name: *mut EGLint,
        handle: *mut EGLint,
        stride: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        image: EGLImageKHR,
        fourcc: *mut ::std::os::raw::c_int,
        num_planes: *mut ::std::os::raw::c_int,
        modifiers: *mut EGLuint64KHR,
    ) -> EGLBoolean,
>;
pub type PFNEGLEXPORTDMABUFIMAGEMESAPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        image: EGLImageKHR,
        fds: *mut ::std::os::raw::c_int,
        strides: *mut EGLint,
        offsets: *mut EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLGETDISPLAYDRIVERCONFIGPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay) -> *mut ::std::os::raw::c_char>;
pub type PFNEGLGETDISPLAYDRIVERNAMEPROC =
    ::std::option::Option<unsafe extern "C" fn(dpy: EGLDisplay) -> *const ::std::os::raw::c_char>;
pub type PFNEGLSWAPBUFFERSREGIONNOKPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        numRects: EGLint,
        rects: *const EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSWAPBUFFERSREGION2NOKPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        numRects: EGLint,
        rects: *const EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYNATIVEDISPLAYNVPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, display_id: *mut EGLNativeDisplayType) -> EGLBoolean,
>;
pub type PFNEGLQUERYNATIVEWINDOWNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surf: EGLSurface,
        window: *mut EGLNativeWindowType,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYNATIVEPIXMAPNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surf: EGLSurface,
        pixmap: *mut EGLNativePixmapType,
    ) -> EGLBoolean,
>;
pub type PFNEGLPOSTSUBBUFFERNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        surface: EGLSurface,
        x: EGLint,
        y: EGLint,
        width: EGLint,
        height: EGLint,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        num_modifiers: EGLint,
        modifiers: *const EGLuint64KHR,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        timeout: EGLTime,
        event: *mut EGLenum,
        aux: *mut EGLAttrib,
    ) -> EGLint,
>;
pub type PFNEGLSTREAMACQUIREIMAGENVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        pImage: *mut EGLImage,
        sync: EGLSync,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMRELEASEIMAGENVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        image: EGLImage,
        sync: EGLSync,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        attrib_list: *const EGLAttrib,
    ) -> EGLBoolean,
>;
pub type PFNEGLSTREAMFLUSHNVPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type PFNEGLQUERYDISPLAYATTRIBNVPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, attribute: EGLint, value: *mut EGLAttrib) -> EGLBoolean,
>;
pub type PFNEGLSETSTREAMMETADATANVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        n: EGLint,
        offset: EGLint,
        size: EGLint,
        data: *const ::std::os::raw::c_void,
    ) -> EGLBoolean,
>;
pub type PFNEGLQUERYSTREAMMETADATANVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        name: EGLenum,
        n: EGLint,
        offset: EGLint,
        size: EGLint,
        data: *mut ::std::os::raw::c_void,
    ) -> EGLBoolean,
>;
pub type PFNEGLRESETSTREAMNVPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, stream: EGLStreamKHR) -> EGLBoolean,
>;
pub type PFNEGLCREATESTREAMSYNCNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        stream: EGLStreamKHR,
        type_: EGLenum,
        attrib_list: *const EGLint,
    ) -> EGLSyncKHR,
>;
pub type EGLSyncNV = *mut ::std::os::raw::c_void;
pub type EGLTimeNV = khronos_utime_nanoseconds_t;
pub type PFNEGLCREATEFENCESYNCNVPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        condition: EGLenum,
        attrib_list: *const EGLint,
    ) -> EGLSyncNV,
>;
pub type PFNEGLDESTROYSYNCNVPROC =
    ::std::option::Option<unsafe extern "C" fn(sync: EGLSyncNV) -> EGLBoolean>;
pub type PFNEGLFENCENVPROC =
    ::std::option::Option<unsafe extern "C" fn(sync: EGLSyncNV) -> EGLBoolean>;
pub type PFNEGLCLIENTWAITSYNCNVPROC = ::std::option::Option<
    unsafe extern "C" fn(sync: EGLSyncNV, flags: EGLint, timeout: EGLTimeNV) -> EGLint,
>;
pub type PFNEGLSIGNALSYNCNVPROC =
    ::std::option::Option<unsafe extern "C" fn(sync: EGLSyncNV, mode: EGLenum) -> EGLBoolean>;
pub type PFNEGLGETSYNCATTRIBNVPROC = ::std::option::Option<
    unsafe extern "C" fn(sync: EGLSyncNV, attribute: EGLint, value: *mut EGLint) -> EGLBoolean,
>;
pub type EGLuint64NV = khronos_utime_nanoseconds_t;
pub type PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC =
    ::std::option::Option<unsafe extern "C" fn() -> EGLuint64NV>;
pub type PFNEGLGETSYSTEMTIMENVPROC = ::std::option::Option<unsafe extern "C" fn() -> EGLuint64NV>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_display {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_resource {
    _unused: [u8; 0],
}
pub type PFNEGLBINDWAYLANDDISPLAYWLPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, display: *mut wl_display) -> EGLBoolean,
>;
pub type PFNEGLUNBINDWAYLANDDISPLAYWLPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, display: *mut wl_display) -> EGLBoolean,
>;
pub type PFNEGLQUERYWAYLANDBUFFERWLPROC = ::std::option::Option<
    unsafe extern "C" fn(
        dpy: EGLDisplay,
        buffer: *mut wl_resource,
        attribute: EGLint,
        value: *mut EGLint,
    ) -> EGLBoolean,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wl_buffer {
    _unused: [u8; 0],
}
pub type PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC = ::std::option::Option<
    unsafe extern "C" fn(dpy: EGLDisplay, image: EGLImageKHR) -> *mut wl_buffer,
>;
